### ISSUE TITLE
No module named 'NCubeReprojectFilter'

### ISSUE THREAD

**Issue by rvalenzuelar** [mobigroup/ParaView-plugins#1]
After following the instructions for installation (loading the NCubeParaViewPlugin.py file) I get the following message:
```python
./pv5.9.sh
<class 'ModuleNotFoundError'>
(  92.456s) [paraview        ]vtkPVPythonAlgorithmPlu:187   WARN| Failed to load Python plugin:
Failed to call `paraview.detail.pythonalgorithm.load_plugin`.
Traceback (most recent call last):
  File "/Applications/ParaView-5.9.1.app/Contents/Python/paraview/detail/pythonalgorithm.py", line 509, in load_plugin
    spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/raulvalenzuela/Downloads/ParaView-plugins-master/NCube/NCubeParaViewPlugin.py", line 16, in <module>
    from NCubeReprojectFilter import *
ModuleNotFoundError: No module named 'NCubeReprojectFilter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/ParaView-5.9.1.app/Contents/Python/paraview/detail/pythonalgorithm.py", line 513, in load_plugin
    module = imp.load_source(modulename, filepath)
  File "/Applications/ParaView-5.9.1.app/Contents/Libraries/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/raulvalenzuela/Downloads/ParaView-plugins-master/NCube/NCubeParaViewPlugin.py", line 16, in <module>
    from NCubeReprojectFilter import *
ModuleNotFoundError: No module named 'NCubeReprojectFilter'
(  92.600s) [paraview        ]  vtkPVPluginLoader.cxx:530    ERR| vtkPVPluginLoader (0x7fefd4438bf0): dlopen(/Users/raulvalenzuela/Downloads/ParaView-plugins-master/NCube/NCubeParaViewPlugin.py, 1): no suitable image found.  Did find:
	/Users/raulvalenzuela/Downloads/ParaView-plugins-master/NCube/NCubeParaViewPlugin.py: file too short
	/Users/raulvalenzuela/Downloads/ParaView-plugins-master/NCube/NCubeParaViewPlugin.py: file too short
```

It seems that `NCubeReprojectFilter.py` is missing in the package.

**Comment by AlexeyPechnikov** [comment]
Please use stable branch "python3.8": https://github.com/mobigroup/ParaView-plugins/tree/python3.8

**Comment by s1291** [comment]
For me, I fixed that by commenting out this [line](https://github.com/AlexeyPechnikov/ParaView-plugins/blob/2ee747dbd6e076c0948d13933ba8f09c8ffd15cb/NCube/NCubeParaViewPlugin.py#L16C1-L16C35):

```py
# from NCubeReprojectFilter import *
```
